test:
  sessions:
    default:
      database: test_mongoid_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
development:
  options:
    raise_not_found_error: false
  sessions:
    default:  &defaults
      use_utc: false
      use_activesupport_time_zone: true
      database: test_mongoid_production
      hosts:
        - localhost:27017
      options:
        consistency: :strong
