require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompinfosController do

  # This should return the minimal set of attributes required to create a valid
  # Compinfo. As you add validations to Compinfo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompinfosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all compinfos as @compinfos" do
      compinfo = Compinfo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:compinfos).should eq([compinfo])
    end
  end

  describe "GET show" do
    it "assigns the requested compinfo as @compinfo" do
      compinfo = Compinfo.create! valid_attributes
      get :show, {:id => compinfo.to_param}, valid_session
      assigns(:compinfo).should eq(compinfo)
    end
  end

  describe "GET new" do
    it "assigns a new compinfo as @compinfo" do
      get :new, {}, valid_session
      assigns(:compinfo).should be_a_new(Compinfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested compinfo as @compinfo" do
      compinfo = Compinfo.create! valid_attributes
      get :edit, {:id => compinfo.to_param}, valid_session
      assigns(:compinfo).should eq(compinfo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Compinfo" do
        expect {
          post :create, {:compinfo => valid_attributes}, valid_session
        }.to change(Compinfo, :count).by(1)
      end

      it "assigns a newly created compinfo as @compinfo" do
        post :create, {:compinfo => valid_attributes}, valid_session
        assigns(:compinfo).should be_a(Compinfo)
        assigns(:compinfo).should be_persisted
      end

      it "redirects to the created compinfo" do
        post :create, {:compinfo => valid_attributes}, valid_session
        response.should redirect_to(Compinfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved compinfo as @compinfo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compinfo.any_instance.stub(:save).and_return(false)
        post :create, {:compinfo => {}}, valid_session
        assigns(:compinfo).should be_a_new(Compinfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compinfo.any_instance.stub(:save).and_return(false)
        post :create, {:compinfo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested compinfo" do
        compinfo = Compinfo.create! valid_attributes
        # Assuming there are no other compinfos in the database, this
        # specifies that the Compinfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Compinfo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => compinfo.to_param, :compinfo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested compinfo as @compinfo" do
        compinfo = Compinfo.create! valid_attributes
        put :update, {:id => compinfo.to_param, :compinfo => valid_attributes}, valid_session
        assigns(:compinfo).should eq(compinfo)
      end

      it "redirects to the compinfo" do
        compinfo = Compinfo.create! valid_attributes
        put :update, {:id => compinfo.to_param, :compinfo => valid_attributes}, valid_session
        response.should redirect_to(compinfo)
      end
    end

    describe "with invalid params" do
      it "assigns the compinfo as @compinfo" do
        compinfo = Compinfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compinfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => compinfo.to_param, :compinfo => {}}, valid_session
        assigns(:compinfo).should eq(compinfo)
      end

      it "re-renders the 'edit' template" do
        compinfo = Compinfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compinfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => compinfo.to_param, :compinfo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested compinfo" do
      compinfo = Compinfo.create! valid_attributes
      expect {
        delete :destroy, {:id => compinfo.to_param}, valid_session
      }.to change(Compinfo, :count).by(-1)
    end

    it "redirects to the compinfos list" do
      compinfo = Compinfo.create! valid_attributes
      delete :destroy, {:id => compinfo.to_param}, valid_session
      response.should redirect_to(compinfos_url)
    end
  end

end
